services:
  db:
    image: postgres:16-alpine
    container_name: order-cinema-db
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - order-cinema-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: order-cinema-rabbitmq
    env_file:
      - .env.development
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - order-cinema-network  
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5672 && nc -z 127.0.0.1 15672"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 60s

  redis:
    image: redis:7-alpine
    container_name: order-cinema-redis
    env_file:
      - .env.development
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379" 
    networks:
      - order-cinema-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  order-cinema-network:
    driver: bridge
